[config]
default_to_workspace = false

[tasks.ignore-members]
workspace = false

[tasks.clean]
command = "cargo"
args = ["clean"]

[tasks.install-wasm]
command = "rustup"
args = ["add", "target", "wasm32-unknown-unknown"]

[tasks.check]
command = "cargo"
args = ["check", "--all-features"]

[tasks.build]
command = "cargo"
args = ["build", "--release"]

[tasks.test]
command = "cargo"
args = ["test", "--release", "--all-features"]

[tasks.format_inst]
[tasks.format-inst]
install_crate = {crate_name = "rustfmt", rustup_component_name = "rustfmt", binary = "rustfmt", test_arg = "--help"}

[tasks.format]
dependencies = ["format-inst"]
command = "cargo"
args = ["fmt"]

[tasks.format-check]
dependencies = ["format-inst"]
command = "cargo"
args = ["fmt", "--check"]

[tasks.clippy-inst]
install_crate = {crate_name = "clippy", rustup_component_name = "clippy", binary = "clippy", test_arg = "--help"}

[tasks.clippy]
dependencies = ["clippy-inst"]
command = "cargo"
args = ["clippy", "--", "--deny", "warnings"]

[tasks.audit-inst]
command = "cargo"
args = ["install", "cargo-audit"]

[tasks.audit]
dependencies = ["audit-inst"]
command = "cargo"
args = ["audit"]

[tasks.cov]
command = "cargo"
args = ["llvm-cov", "--workspace", "--lcov", "--output-path", "lcov.info"]

[tasks.zepter-inst]
command = "cargo"
args = ["install", "zepter", "--locked"]

[tasks.zepter-check]
dependencies = ["zepter-inst"]
command = "zepter"
args = ["run", "check"]

[tasks.zepter-format]
dependencies = ["zepter-inst"]
command = "zepter"
args = ["run", "format"]

[tasks.zepter-fix-check]
dependencies = ["zepter-inst"]
command = "zepter"
args = ["run", "check-fix"]

[tasks.zepter-fix-format]
dependencies = ["zepter-inst"]
command = "zepter"
args = ["run", "format-fix"]

[tasks.zepter]
dependencies = ["zepter-fix-check", "zepter-fix-format"]

[tasks.udeps-inst]
toolchain = "nightly"
command = "cargo"
args = ["install", "cargo-udeps", "--locked"]

[tasks.udeps]
dependencies = ["udeps-inst"]
toolchain = "nightly"
command = "cargo"
args = ["udeps", "--all-targets"]

[tasks.machete]
command = "cargo"
args = ["machete"]


[tasks.quick-check]
dependencies = ["format-check", "zepter-format", "zepter-check"]

[tasks.quick-fix]
dependencies = ["format", "zepter"]

[tasks.dependencies-check]
dependencies = ["audit", "machete"]

[tasks.ci-common]
dependencies = ["check", "build", "test", "clippy", "dependencies-check"]

[tasks.ci]
dependencies = ["quick-fix", "ci-common"]

[tasks.ci-remote]
dependencies = ["quick-check", "ci-common"]
