[settings]
timeout = 3600

[relaychain]
chain = "local"
default_command = "./relay-bin/zkv-relay"

[[relaychain.nodes]]
name = "alice"
validator = true
ws_port = 9955
rpc_port = 8855

[[relaychain.nodes]]
name = "bob"
validator = true
ws_port = 9944
rpc_port = 8844

[relaychain.genesis.runtimeGenesis.patch.configuration.config.scheduler_params]
lookahead = 2

[relaychain.genesis.runtimeGenesis.patch.configuration.config.async_backing_params]
max_candidate_depth = 3
allowed_ancestry_len = 2

[[parachains]]
id = 1
add_to_genesis = true
cumulus_based = true
force_decorator = "generic-evm"
chain = "dev"

[[parachains.collators]]
name = "vflow-parachain-collator01"
command = "./target/release/vflow-node"
ws_port = 9933
rpc_port = 8833
args = ["-lxcm=trace", "--rpc-max-connections 10000"]

[[parachains.collators]]
name = "vflow-parachain-collator02"
ws_port = 9922
rpc_port = 8822
command = "./target/release/vflow-node"
args = ["--rpc-max-connections 10000"]
