DEFAULT_BM_STEPS=50
DEFAULT_BM_REPEAT=20
DEFAULT_BM_HEAP_PAGES=4096
NODE_CRATE="vflow-node"
PROFILE=${PROFILE:-"production"}
DEFAULT_NODE_EXE="target/${PROFILE}/${NODE_CRATE}"
RUNTIME_CRATE="vflow-runtime"
WASM_FILE="${RUNTIME_CRATE}.compact.compressed.wasm"
DEFAULT_WASM="target/${PROFILE}/wbuild/${RUNTIME_CRATE}/${WASM_FILE}"
TEMPLATES_ROOT=${TEMPLATES_ROOT:-"scripts/templates"}
DEFAULT_LOCAL_WEIGHT_TEMPLATE="${TEMPLATES_ROOT}/pallets-weight-template.hbs"
IMAGE=${IMAGE:-"vflow"}
DEFAULT_DOCKER_FILE=${DEFAULT_DOCKER_FILE:-"docker/dockerfiles/vflow-node.Dockerfile"}



# The following line ensure we know the project root
PROJECT_ROOT=${PROJECT_ROOT:-$(git rev-parse --show-toplevel)}
WEIGHT_OUT_PATH=${WEIGHT_OUT_PATH:-""}
NODE_EXE=${NODE_EXE:-"${PROJECT_ROOT}/${DEFAULT_NODE_EXE}"}
RUNTIME=${RUNTIME:-"${PROJECT_ROOT}/${DEFAULT_WASM}"}
BM_STEPS=${BM_STEPS:-${DEFAULT_BM_STEPS}}
BM_REPEAT=${BM_REPEAT:-${DEFAULT_BM_REPEAT}}
BM_HEAP_PAGES=${BM_HEAP_PAGES:-${DEFAULT_BM_HEAP_PAGES}}
DOCKER_FILE=${DOCKER_FILE:-"${PROJECT_ROOT}/${DEFAULT_DOCKER_FILE}"}
