// Copyright 2024, Horizen Labs, Inc.
// SPDX-License-Identifier: Apache-2.0

// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// 	http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//! Autogenerated weights for `frame_system_extensions`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 46.2.0
//! DATE: 2025-06-04, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `miklap`, CPU: `11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz`
//! WASM-EXECUTION: `Compiled`, CHAIN: `None`, DB CACHE: `1024`

// Executed Command:
// ./target/release/zkv-para-evm-node
// benchmark
// pallet
// --genesis-builder=spec
// --pallet
// frame_system_extensions
// --extrinsic
// *
// --steps
// 50
// --repeat
// 20
// --heap-pages=4096
// --header
// /home/mdamico/devel/zkVerify-EVM-Parachain/HEADER-APACHE2
// --output
// ./runtime/src/weights/frame_system_extensions.rs
// --template
// ./scripts/templates/deploy-weight-template.hbs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use core::marker::PhantomData;

/// Weights for `frame_system_extensions` using the zkVerify node and recommended hardware.
pub struct ZKVEvmWeight<T>(PhantomData<T>);

use crate::weights_aliases::*;

impl<T: frame_system::Config> frame_system_extensions::WeightInfo for ZKVEvmWeight<T> {
    fn check_genesis() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `30`
        //  Estimated: `0`
        // Minimum execution time: 3_401_000 picoseconds.
        Weight::from_parts(3_579_000, 0)
    }
    fn check_mortality_mortal_transaction() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `68`
        //  Estimated: `0`
        // Minimum execution time: 6_572_000 picoseconds.
        Weight::from_parts(6_806_000, 0)
    }
    fn check_mortality_immortal_transaction() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `68`
        //  Estimated: `0`
        // Minimum execution time: 6_749_000 picoseconds.
        Weight::from_parts(7_016_000, 0)
    }
    fn check_non_zero_sender() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `0`
        //  Estimated: `0`
        // Minimum execution time: 646_000 picoseconds.
        Weight::from_parts(698_000, 0)
    }
    /// Storage: `System::Account` (r:1 w:1)
    /// Proof: `System::Account` (`max_values`: None, `max_size`: Some(116), added: 2591, mode: `MaxEncodedLen`)
    fn check_nonce() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `129`
        //  Estimated: `3581`
        // Minimum execution time: 7_987_000 picoseconds.
        Weight::from_parts(8_137_000, 3581)
            .saturating_add(T::DbWeight::get().reads(1_u64))
            .saturating_add(T::DbWeight::get().writes(1_u64))
    }
    fn check_spec_version() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `0`
        //  Estimated: `0`
        // Minimum execution time: 516_000 picoseconds.
        Weight::from_parts(568_000, 0)
    }
    fn check_tx_version() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `0`
        //  Estimated: `0`
        // Minimum execution time: 507_000 picoseconds.
        Weight::from_parts(545_000, 0)
    }
    fn check_weight() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `0`
        //  Estimated: `0`
        // Minimum execution time: 3_855_000 picoseconds.
        Weight::from_parts(4_014_000, 0)
    }
}
