
//! Autogenerated weights for `pallet_permissioned_deploy`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 43.0.0
//! DATE: 2025-04-17, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `DESKTOP-37J5UBI`, CPU: `Intel(R) Core(TM) Ultra 9 185H`
//! WASM-EXECUTION: `Compiled`, CHAIN: `None`, DB CACHE: `1024`

// Executed Command:
// ./target/debug/zkv-para-evm-node
// benchmark
// pallet
// --pallet
// pallet-permissioned-deploy
// --extrinsic
// 
// --output
// weights.rs
// --template
// pallets/benchmarking/frame-weight-template.hbs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use core::marker::PhantomData;

/// Weight functions needed for `pallet_permissioned_deploy`.
pub trait WeightInfo {
	fn grant_deploy_permission() -> Weight;
	fn revoke_deploy_permission() -> Weight;
}

/// Weights for `pallet_permissioned_deploy` using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	/// Storage: `PermissionedDeploy::Deployers` (r:0 w:1)
	/// Proof: `PermissionedDeploy::Deployers` (`max_values`: None, `max_size`: Some(36), added: 2511, mode: `MaxEncodedLen`)
	fn grant_deploy_permission() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 83_982_000 picoseconds.
		Weight::from_parts(93_156_000, 0)
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `PermissionedDeploy::Deployers` (r:0 w:1)
	/// Proof: `PermissionedDeploy::Deployers` (`max_values`: None, `max_size`: Some(36), added: 2511, mode: `MaxEncodedLen`)
	fn revoke_deploy_permission() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 86_127_000 picoseconds.
		Weight::from_parts(90_724_000, 0)
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
}

// For backwards compatibility and tests.
impl WeightInfo for () {
	/// Storage: `PermissionedDeploy::Deployers` (r:0 w:1)
	/// Proof: `PermissionedDeploy::Deployers` (`max_values`: None, `max_size`: Some(36), added: 2511, mode: `MaxEncodedLen`)
	fn grant_deploy_permission() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 83_982_000 picoseconds.
		Weight::from_parts(93_156_000, 0)
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `PermissionedDeploy::Deployers` (r:0 w:1)
	/// Proof: `PermissionedDeploy::Deployers` (`max_values`: None, `max_size`: Some(36), added: 2511, mode: `MaxEncodedLen`)
	fn revoke_deploy_permission() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 86_127_000 picoseconds.
		Weight::from_parts(90_724_000, 0)
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
}
